#!/usr/bin/env python3
"""
Loader для загрузки платформы V3 в Home Assistant PyScript

Этот скрипт:
1. Копирует файлы ядра в директорию pyscript
2. Создаёт конфигурационный файл pyscript.yaml
3. Опционально перезагружает PyScript через HA API
"""

import os
import sys
import shutil
from pathlib import Path
from typing import Optional


class PyscriptLoader:
    """Загрузчик платформы V3 в Home Assistant PyScript"""
    
    def __init__(self, ha_config_dir: Optional[str] = None):
        """
        Инициализация загрузчика
        
        Args:
            ha_config_dir: Путь к директории конфигурации HA.
                          Если None, используется стандартный путь ~/.homeassistant
        """
        self.source_dir = Path(__file__).parent
        self.ha_config_dir = Path(ha_config_dir) if ha_config_dir else Path.home() / ".homeassistant"
        self.pyscript_dir = self.ha_config_dir / "pyscript"
        
    def copy_core_files(self) -> list[Path]:
        """Копировать файлы ядра в pyscript"""
        copied = []
        
        # Создаём директорию core в pyscript
        target_core_dir = self.pyscript_dir / "platform_v3" / "core"
        target_core_dir.mkdir(parents=True, exist_ok=True)
        
        # Копируем файлы core
        source_core_dir = self.source_dir / "core"
        for py_file in source_core_dir.glob("*.py"):
            target_file = target_core_dir / py_file.name
            shutil.copy2(py_file, target_file)
            copied.append(target_file)
            print(f"✓ Скопировано: {py_file.name} -> {target_core_dir}")
        
        return copied
    
    def copy_features_files(self) -> list[Path]:
        """Копировать файлы фич в pyscript"""
        copied = []
        
        # Создаём директорию features в pyscript
        target_features_dir = self.pyscript_dir / "platform_v3" / "features"
        target_features_dir.mkdir(parents=True, exist_ok=True)
        
        # Копируем файлы features
        source_features_dir = self.source_dir / "features"
        for py_file in source_features_dir.glob("*.py"):
            if py_file.name != "__init__.py":  # Пропускаем __init__.py
                target_file = target_features_dir / py_file.name
                shutil.copy2(py_file, target_file)
                copied.append(target_file)
                print(f"✓ Скопировано: {py_file.name} -> {target_features_dir}")
        
        return copied
    
    def copy_adapters_files(self) -> list[Path]:
        """Копировать файлы адаптеров в pyscript"""
        copied = []
        
        # Создаём директорию adapters в pyscript
        target_adapters_dir = self.pyscript_dir / "platform_v3" / "adapters"
        target_adapters_dir.mkdir(parents=True, exist_ok=True)
        
        # Копируем файлы adapters
        source_adapters_dir = self.source_dir / "adapters"
        for py_file in source_adapters_dir.glob("*.py"):
            if py_file.name != "__init__.py":  # Пропускаем __init__.py
                target_file = target_adapters_dir / py_file.name
                shutil.copy2(py_file, target_file)
                copied.append(target_file)
                print(f"✓ Скопировано: {py_file.name} -> {target_adapters_dir}")
        
        return copied
    
    def create_pyscript_yaml(self) -> Path:
        """Создать файл конфигурации pyscript.yaml"""
        pyscript_yaml = self.pyscript_dir / "pyscript.yaml"
        
        config_content = """# Platform V3 Configuration
# Auto-generated by loader.py

# Allow imports from platform_v3 directory
allow_all_imports: true

# Enable state persistence (optional)
# state_change_listener: true

# Logging settings
logging:
  level: info
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s
"""
        
        with open(pyscript_yaml, 'w') as f:
            f.write(config_content)
        
        print(f"✓ Создан конфиг: {pyscript_yaml}")
        return pyscript_yaml
    
    def create_init_script(self) -> Path:
        """Создать главный скрипт инициализации"""
        init_script = self.pyscript_dir / "platform_v3_init.py"
        
        init_content = '''"""
Platform V3 - Инициализация

Этот скрипт запускается при старте PyScript и инициализирует платформу.
"""

import sys
from pathlib import Path

# Добавляем platform_v3 в path
platform_dir = Path(__file__).parent / "platform_v3"
sys.path.insert(0, str(platform_dir))

# Импортируем компоненты
from core.fsm import FSMEngine
from core.event_bus import EventBus
from core.logger import Logger
from core.registry import Registry
from adapters.ha_adapter import HAAdapter

# Создаём глобальные экземпляры
event_bus = EventBus()
logger = Logger(component="platform_v3")
fsm_engine = FSMEngine(event_bus, logger)
registry = Registry()
ha_adapter = HAAdapter()

# Регистрируем адаптер в FSM
fsm_engine.set_adapter(ha_adapter)

# Импортируем и регистрируем автоматы
from features.lighting import create_lighting_automations
from features.climate import create_climate_automations

# Конфигурация комнат и зон (можно вынести в variables.yaml)
ROOMS = ["living_room", "bedroom", "kitchen", "bathroom"]
ZONES = ["zone_1", "zone_2"]

# Создаём и регистрируем автоматы
lighting_defs = create_lighting_automations(ROOMS)
climate_defs = create_climate_automations(ZONES)

for definition in lighting_defs + climate_defs:
    fsm_engine.register(definition)
    logger.info(f"Зарегистрирован автомат: {definition.entity_id}")

logger.info(f"Platform V3 запущена. Всего автоматов: {len(lighting_defs) + len(climate_defs)}")


# Обработчики событий от HA
@state_changed("*")
def handle_state_change(entity_id, old_state, new_state):
    """Обработка изменений состояний устройств"""
    # Публикуем событие в шину
    event_bus.publish("device.state_changed", {
        "entity_id": entity_id,
        "old_state": old_state,
        "new_state": new_state
    })


# Сервисы для отладки
@service
def fsm_debug(entity_id: str):
    """Показать состояние автомата"""
    state = fsm_engine.get_state(entity_id)
    if state:
        logger.info(f"Состояние {entity_id}: {state.current}")
        return {"state": state.current, "history": state.history}
    return {"error": "Автомат не найден"}


@service
def fsm_reset(entity_id: str):
    """Сбросить автомат в начальное состояние"""
    result = fsm_engine.reset(entity_id)
    logger.info(f"Сброшен автомат {entity_id}: {result}")
    return {"success": result}


@service
def fsm_trigger(entity_id: str, trigger: str, **context):
    """Вызвать триггер вручную"""
    result = fsm_engine.trigger(entity_id, trigger, context)
    logger.info(f"Триггер {trigger} для {entity_id}: {result}")
    return {"success": result}
'''
        
        with open(init_script, 'w') as f:
            f.write(init_content)
        
        print(f"✓ Создан скрипт инициализации: {init_script}")
        return init_script
    
    def reload_pyscript(self, ha_url: str, ha_token: str) -> bool:
        """Перезагрузить PyScript через HA API"""
        import requests
        
        url = f"{ha_url}/api/services/pyscript/reload"
        headers = {
            "Authorization": f"Bearer {ha_token}",
            "Content-Type": "application/json"
        }
        
        try:
            response = requests.post(url, headers=headers, timeout=10)
            if response.status_code == 200:
                print("✓ PyScript перезапущен")
                return True
            else:
                print(f"✗ Ошибка перезагрузки: {response.status_code}")
                return False
        except Exception as e:
            print(f"✗ Ошибка подключения к HA: {e}")
            return False
    
    def deploy(self, ha_url: Optional[str] = None, ha_token: Optional[str] = None) -> bool:
        """
        Полный процесс деплоя
        
        Args:
            ha_url: URL Home Assistant (опционально, для перезагрузки)
            ha_token: Токен доступа (опционально, для перезагрузки)
        
        Returns:
            bool: Успешность деплоя
        """
        print("\n=== Деплой Platform V3 в Home Assistant ===\n")
        
        # Копируем файлы
        print("1. Копирование файлов ядра...")
        self.copy_core_files()
        
        print("\n2. Копирование файлов фич...")
        self.copy_features_files()
        
        print("\n3. Копирование файлов адаптеров...")
        self.copy_adapters_files()
        
        print("\n4. Создание конфигурации...")
        self.create_pyscript_yaml()
        
        print("\n5. Создание скрипта инициализации...")
        self.create_init_script()
        
        # Перезагружаем PyScript если предоставлены credentials
        if ha_url and ha_token:
            print("\n6. Перезагрузка PyScript...")
            self.reload_pyscript(ha_url, ha_token)
        else:
            print("\n⚠ Перезагрузка PyScript пропущена (нет credentials)")
            print("  Перезапустите PyScript вручную через Developer Tools > Services > pyscript.reload")
        
        print("\n=== Деплой завершён ===\n")
        return True


def main():
    """Точка входа для CLI"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Loader для Platform V3")
    parser.add_argument("--ha-config", help="Путь к директории конфигурации HA")
    parser.add_argument("--ha-url", help="URL Home Assistant (для перезагрузки)")
    parser.add_argument("--token", help="Long-lived token (для перезагрузки)")
    parser.add_argument("--dry-run", action="store_true", help="Тестовый режим без копирования")
    
    args = parser.parse_args()
    
    if args.dry_run:
        print("=== Dry-run режим ===")
        print(f"Директория HA: {args.ha_config or '~/.homeassistant'}")
        print(f"Директория pyscript: {Path(args.ha_config).expanduser() / 'pyscript' if args.ha_config else '~/.homeassistant/pyscript'}")
        print("\nФайлы для копирования:")
        print("  core/*.py -> pyscript/platform_v3/core/")
        print("  features/*.py -> pyscript/platform_v3/features/")
        print("  adapters/*.py -> pyscript/platform_v3/adapters/")
        print("\nФайлы для создания:")
        print("  pyscript/platform_v3/pyscript.yaml")
        print("  pyscript/platform_v3_init.py")
        return
    
    loader = PyscriptLoader(ha_config_dir=args.ha_config)
    success = loader.deploy(ha_url=args.ha_url, ha_token=args.token)
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
